### ISSUE TITLE
Kanban

### ISSUE THREAD

**Issue by Mhamad-Raad** [Mhamad-Raad/ruby-on-rails-capstone#11]
# Kanban
## In this issue we have finished the project and task division between us (TWO MAN ARMY).
Link of the project: https://github.com/users/Mhamad-Raad/projects/5
### Done 🎉💯 🔥

**Comment by omarsalem7** [comment]
Hi @Mhamad-Raad , @Camilovelag 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/j7vckgz15cAYmxatzB/giphy.gif)

## Highlights
- Tasks assigned equally ✔️
- The columns of the kanban board were created correctly ✔️

## Required Changes ♻️

- [ ] There are some cards doesn't have a description, so kindly add a description for all cards. 
- [ ] Also you forget to add a card for specs, so kindly add a card for that.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by omarsalem7** [comment]
Hi @Mhamad-Raad , @Camilovelag 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
